Support for ForeignKey
kayac/ddl-maker pull request #32
Opened 2021-09-02 15:42 UTC by ManabuSeki

- Support for ForeignKey of MySQL

see document 
- ja
  - https://dev.mysql.com/doc/refman/8.0/ja/create-table-foreign-keys.html
- en
  - https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html

2021-09-12 07:55 UTC, shmokmt requested changes
@ManabuSeki 
thanks for your pull request 😄 
I found some mistakes for typos.
Please fix it 👀

2021-09-12 07:55 UTC, shmokmt commented on dialect/mysql/mysql.go
> +	foreingKey := ForeignKey{
```suggestion
	foreignKey := ForeignKey{
```

2021-09-12 07:55 UTC, shmokmt commented on dialect/mysql/mysql.go
> +// ToSQL return foreign key sql string
```suggestion
// ToSQL returns foreign key sql string
```

2021-09-13 15:00 UTC, ManabuSeki commented on dialect/mysql/mysql.go
> +// ToSQL return foreign key sql string
The return value is one

2021-09-13 15:01 UTC, ManabuSeki commented on dialect/mysql/mysql.go
> +	foreingKey := ForeignKey{
fixed 107ce6de97ea3ad1750869ba50e8191eaf3e0751

2021-09-14 02:52 UTC, shmokmt approved these changes
thanks!

2021-09-14 02:53 UTC, merged